---
title: "chap11_part_2"
author: "linhnm"
date: "5/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GLM chap 11

ex 11.7
```{r}
# 1,
# có 5 biến giải thích, ứng với số groups là 5, 5, 4, 5, 4 thì df = n - p' = 1975 - 5 - 5 - 4 - 5 - 4 - 1
df0 = 1975 - 5 - 5 - 4 - 5 - 4 - 1
df0
# 
P_size <- 5; T_size <- 5; V_size <- 4; D_size <- 5; C_size <- 4
delta_df_TP <- T_size * P_size
df_TP <- df0 - delta_df_TP
# 2,ước lượng dùng mean deviance = D/(n - p')
c(4695.2/df_TP)
# 3, likelihood: 1 - pchisq(null_dev - dev, df_null - df)

dev <- c(4695.2,4675.9,4640.1,4598.8,4567.3,4497.1,4462.0,4443.4,4420.8,4390.9)
null_dev <- 5050.9
delta_dev <- null_dev - dev
delta_df <- c(T_size*P_size, T_size*V_size, T_size*D_size, T_size*C_size, P_size*D_size, P_size*C_size, V_size*D_size, V_size*C_size, D_size*C_size)
1 - pchisq(delta_dev, delta_df)
```

ex 11.8
```{r}
# 1. AIC cang nho thi mo hinh cang phu hop -> Gamma with log link function
# 2. 
```

ex 11.9
```{r}
data("lime"); str(lime)

lime.m1 <- glm( Foliage ~ Origin * log(DBH), family=Gamma(link="log"),data=lime)
lime.m2 <- glm( Foliage ~ Origin * DBH,family=Gamma(link="log"), data=lime)
par(mfrow=c(2, 3))

scatter.smooth( log(fitted(lime.log)), rstandard(lime.log),col="gray", lwd=2 )
qqnorm( qresid(lime.log)); plot(cooks.distance(lime.log), type="h")
scatter.smooth( log(fitted(lime.m2)), rstandard(lime.m2),col="gray", lwd=2 )
qqnorm( qresid(lime.m2)); plot(cooks.distance(lime.m2), type="h")


# co the thay AIC cua lime.m1 < AIC cua lime.m2 -> lime.m1 tot hon 

#colSums(influence.measures(lime.m1)$is.inf)
#colSums(influence.measures(lime.m2)$is.inf)
#summary(lime.m1)
#summary(lime.m2)
```
ex 11.10
```{r}
lime.m1 <- glm( Foliage ~ Origin * log(DBH), family=Gamma(link="log"),data=lime)
lime.age <- glm( Foliage ~ Origin * log(DBH) + Age, family=Gamma(link="log"),data=lime)

summary(lime.age)
# ta thay rang gia tri p-value cua bien giai thich age > 0.05 -> khong dong gop nhieu vao mo hinh
```



